export type TestInfo = {
  measures: string;
  why: string;
  yours?: string;
  abnormal: string;
  next: string;
};

export const testInfo: Record<string, TestInfo> = {
  "Total cholesterol": {
    measures: "The total cholesterol carried in your blood, including LDL, HDL, and other cholesterol-containing particles.",
    why: "It is part of a lipid panel used to estimate long-term risk of plaque buildup, heart attack, and stroke.",
    yours: "218 mg/dL is above the laboratory goal of less than 200. The LDL, HDL, and non-HDL values explain why this total is elevated.",
    abnormal: "A high result can reflect genetics, saturated-fat intake, weight, diabetes, low thyroid function, kidney disease, or some medicines. Cardiovascular risk depends on the complete profile, not this number alone.",
    next: "Review the complete lipid profile and overall risk with your clinician. Usual first steps include reducing saturated fat, increasing soluble fiber and physical activity, managing weight, avoiding tobacco, and using medication when the overall risk warrants it.",
  },
  "LDL cholesterol": {
    measures: "Low-density lipoprotein cholesterol, the main cholesterol-carrying particle associated with plaque buildup in arteries.",
    why: "LDL is a primary target for cardiovascular risk assessment and cholesterol-lowering treatment.",
    yours: "164 mg/dL is high and is the strongest actionable finding in this report. Current AHA/ACC guidance supports an early risk discussion in young adults when LDL is at least 160 mg/dL.",
    abnormal: "Persistently high LDL increases lifetime risk of atherosclerosis, heart attack, stroke, and peripheral artery disease. Causes can include genetics, diet, metabolic disease, low thyroid function, and certain medicines.",
    next: "Confirm the result and discuss family history and other risk factors. A heart-healthy eating pattern, regular exercise, weight management, and avoiding tobacco help. Your clinician should decide whether lifestyle alone or medication is appropriate.",
  },
  "HDL cholesterol": {
    measures: "High-density lipoprotein cholesterol, which participates in moving cholesterol away from tissues toward the liver.",
    why: "HDL helps place LDL and total cholesterol into cardiovascular-risk context.",
    yours: "30.7 mg/dL is below the laboratory goal of greater than 40 and adds concern to the high LDL and non-HDL pattern.",
    abnormal: "Low HDL is associated with higher cardiovascular risk and may accompany smoking, inactivity, excess weight, insulin resistance, or genetic factors. A high HDL is generally favorable, although it does not cancel a high LDL.",
    next: "Focus on overall risk rather than trying to raise HDL with a specific supplement. Regular aerobic activity, stopping tobacco, improving diet quality, and managing weight can help while LDL reduction remains the main target.",
  },
  "Non-HDL cholesterol": {
    measures: "Total cholesterol minus HDL. It captures cholesterol in LDL, VLDL, and other potentially plaque-forming particles.",
    why: "It is a useful secondary target, especially when triglycerides or other metabolic risks are present.",
    yours: "187 mg/dL is above the laboratory goal of less than 130, confirming a high burden of potentially atherogenic cholesterol.",
    abnormal: "A high value is associated with increased long-term cardiovascular risk and usually tracks with high LDL or triglyceride-rich particles.",
    next: "The same measures that lower LDL generally lower non-HDL cholesterol. Review overall risk, diet, activity, weight, family history, and possible medication with your clinician.",
  },
  "Cholesterol / HDL ratio": {
    measures: "Total cholesterol divided by HDL. It summarizes the balance between total cholesterol and the HDL portion.",
    why: "Some laboratories report it as an additional cardiovascular-risk indicator, although treatment decisions focus more directly on LDL, non-HDL, and overall risk.",
    yours: "7.1 is above the printed goal of less than 4.97 because total cholesterol is elevated and HDL is low.",
    abnormal: "A higher ratio is associated with higher cardiovascular risk. It does not identify the cause and should not be interpreted separately from the individual lipid values.",
    next: "Work on the underlying LDL, non-HDL, and lifestyle risk factors. Recheck with the lipid panel rather than targeting the ratio itself.",
  },
  "Triglycerides": {
    measures: "A form of fat used for energy and stored after excess calories are consumed.",
    why: "Triglycerides help assess cardiovascular and metabolic risk and, at very high levels, pancreatitis risk.",
    yours: "115 mg/dL is within the printed range and is reassuring.",
    abnormal: "High values may occur with excess refined carbohydrates, alcohol, diabetes, excess weight, low thyroid function, kidney or liver disease, genetics, or certain medicines. Very high levels can inflame the pancreas.",
    next: "Maintain a balanced diet, regular activity, healthy weight, and moderate or no alcohol. Persistently high values are managed by addressing the cause and sometimes medication.",
  },
  "VLDL": {
    measures: "Very-low-density lipoprotein, a liver-produced particle that mainly carries triglycerides. It is often estimated from the triglyceride value.",
    why: "It provides additional context about triglyceride-rich, potentially atherogenic particles.",
    yours: "23 mg/dL is within the printed range and is consistent with the normal triglyceride result.",
    abnormal: "A high result commonly accompanies high triglycerides and may be associated with insulin resistance, excess weight, diet, alcohol, or genetic lipid disorders.",
    next: "Management usually targets triglycerides and overall cardiovascular risk through diet, exercise, weight management, metabolic control, and medication when needed.",
  },
  "High-sensitivity CRP": {
    measures: "A very sensitive measurement of C-reactive protein, which the liver produces in response to inflammation.",
    why: "It may be used to add cardiovascular-risk context or to detect low-grade inflammation. It does not locate the source of inflammation.",
    yours: "3.83 mg/L is above the printed range. A single value can be temporarily elevated by infection, injury, dental inflammation, or strenuous exercise.",
    abnormal: "High hs-CRP may reflect acute illness, chronic inflammatory conditions, smoking, obesity, or higher cardiovascular risk. It cannot diagnose any of these by itself.",
    next: "Follow the report instruction to repeat at least two weeks later when fully well and metabolically stable. Address the underlying cause if it remains high rather than treating CRP directly.",
  },
  ESR: {
    measures: "How quickly red blood cells settle in a tube. Inflammation can make them clump and settle faster.",
    why: "It is a nonspecific screen used with symptoms and other tests to look for or monitor inflammation.",
    yours: "7 mm/hr is within the printed range, so this test does not show an elevated sedimentation rate.",
    abnormal: "A high ESR can occur with infection, autoimmune disease, inflammatory disorders, anemia, kidney disease, or some cancers. A normal ESR does not exclude every inflammatory condition.",
    next: "No action is usually needed for an in-range ESR by itself. Abnormal results are interpreted with symptoms, CRP, blood counts, and condition-specific testing.",
  },
  "Iron saturation": {
    measures: "The percentage of iron-binding sites on transferrin that are carrying iron.",
    why: "It helps estimate how much iron is readily available for red-cell production and is interpreted with iron, TIBC, ferritin, and the CBC.",
    yours: "17.8% is mildly below the printed range, but ferritin and hemoglobin are normal, so the report does not show iron-deficiency anemia.",
    abnormal: "Low saturation can occur with early iron deficiency, reduced absorption, blood loss, inflammation, or day-to-day variation. High saturation may suggest iron overload or excess supplementation.",
    next: "Ask whether a repeat morning or fasting iron panel is appropriate. Review diet, blood donation, digestive symptoms, and any bleeding. Do not start iron unless deficiency and the reason for it are confirmed.",
  },
  Iron: {
    measures: "The amount of circulating iron bound mainly to transferrin at the time of the blood draw.",
    why: "It helps investigate iron deficiency or overload but varies during the day and is not interpreted alone.",
    yours: "69.76 ug/dL is within the printed range.",
    abnormal: "Low iron can occur with iron deficiency, inflammation, blood loss, or poor absorption. High iron can occur with overload, liver injury, hemolysis, or supplements.",
    next: "Interpret it with ferritin, saturation, TIBC, and the CBC. Treat a confirmed cause, not an isolated serum iron number.",
  },
  TIBC: {
    measures: "Total iron-binding capacity, an estimate of how much iron transferrin could carry if its binding sites were filled.",
    why: "It helps distinguish patterns of iron deficiency, inflammation, and iron overload.",
    yours: "392 ug/dL is within the printed range and near its upper end. Together with the low saturation, it supports repeating the iron assessment if clinically appropriate.",
    abnormal: "A high TIBC often occurs with iron deficiency. A low TIBC may occur with inflammation, liver disease, malnutrition, or iron overload.",
    next: "Use the full iron panel and CBC. If the pattern persists, a clinician may evaluate intake, absorption, blood loss, inflammation, and other causes.",
  },
  Ferritin: {
    measures: "Ferritin, the main iron-storage protein. Blood ferritin estimates stored iron.",
    why: "It is commonly used to look for depleted iron stores or iron overload.",
    yours: "109 ng/mL is within the printed range, making severely depleted iron stores less likely.",
    abnormal: "Low ferritin strongly supports iron deficiency. High ferritin can reflect iron overload, but it can also rise with inflammation, infection, liver disease, obesity, or other illness.",
    next: "Interpret ferritin with saturation, CBC, symptoms, and inflammation markers. Supplements or iron-removal treatment should be based on a confirmed diagnosis.",
  },
  UIBC: {
    measures: "Unsaturated iron-binding capacity, the portion of transferrin binding sites not currently occupied by iron.",
    why: "It is used with serum iron to calculate TIBC and iron saturation.",
    yours: "The report shows 322 but does not print a reference range, so this value should not be labeled high or low from the supplied page alone.",
    abnormal: "A high UIBC can accompany iron deficiency, while a low UIBC can occur with iron overload or reduced transferrin. Interpretation depends on the rest of the iron panel.",
    next: "Use the laboratory's own reference interval and the complete iron pattern. No treatment should be based on UIBC alone.",
  },
  Transferrin: {
    measures: "A liver-made protein that transports iron through the blood.",
    why: "It helps assess the body's iron-carrying capacity and provides context for saturation.",
    yours: "279.85 mg/dL is within the printed range.",
    abnormal: "High transferrin can occur with iron deficiency. Low transferrin may occur with inflammation, liver disease, kidney protein loss, or poor nutrition.",
    next: "Interpret it with iron, ferritin, saturation, liver markers, and clinical history. Address a confirmed underlying cause.",
  },
  "Vitamin D 25-OH": {
    measures: "25-hydroxyvitamin D, the main blood marker of vitamin D obtained from food, supplements, and sun exposure.",
    why: "It is used to assess vitamin D status when deficiency risk, bone concerns, malabsorption, or related symptoms are present.",
    yours: "29 ng/mL is one point below this laboratory's range. NIH guidance considers 20 ng/mL or more adequate for most people, so this is borderline rather than clearly deficient.",
    abnormal: "Low levels can contribute to poor bone mineralization and muscle weakness. Causes include limited intake or sun exposure, malabsorption, obesity, kidney or liver disease, and some medicines. Excess supplementation can cause toxicity.",
    next: "Discuss food sources, safe sun exposure, and whether a modest supplement is appropriate. Avoid high-dose vitamin D without clinician guidance and recheck only when clinically useful.",
  },
  "Vitamin B12": {
    measures: "Vitamin B12, which is needed for red-cell formation, DNA production, and normal nerve function.",
    why: "It may be checked for anemia, numbness, cognitive symptoms, dietary risk, malabsorption, or medicine-related deficiency.",
    yours: "502 pg/mL is within the printed range.",
    abnormal: "Low B12 can cause macrocytic anemia and potentially lasting nerve problems. Causes include vegan diets without supplementation, pernicious anemia, intestinal disease, surgery, and some medicines. High levels often reflect supplements but may require context.",
    next: "No correction is usually needed for an in-range result. Confirm true deficiency with clinical context and sometimes methylmalonic acid before selecting oral or injected replacement.",
  },
  Folate: {
    measures: "Folate, or vitamin B9, which supports DNA formation and red-cell production.",
    why: "It is often checked with B12 when evaluating macrocytic anemia, poor diet, malabsorption, or increased nutritional needs.",
    yours: "10.1 ng/mL is above the printed minimum and is reassuring.",
    abnormal: "Low folate can cause macrocytic anemia and may result from poor intake, alcohol use, malabsorption, increased need, or certain medicines. High intake can mask the anemia of B12 deficiency while nerve injury continues.",
    next: "Maintain folate-rich foods. If low, identify the cause and check B12 before or alongside supplementation.",
  },
  "Hemoglobin A1c": {
    measures: "The percentage of hemoglobin with glucose attached, reflecting average blood sugar over roughly the previous two to three months.",
    why: "It is used to screen for and monitor prediabetes and diabetes.",
    yours: "5.5% is in the non-diabetic range below 5.7%.",
    abnormal: "Values from 5.7% to 6.4% suggest prediabetes and 6.5% or higher may indicate diabetes when confirmed. Anemia, altered red-cell lifespan, kidney disease, hemoglobin variants, and pregnancy can affect accuracy.",
    next: "Maintain regular activity, a fiber-rich eating pattern, healthy weight, and appropriate screening intervals. An abnormal screening result is usually confirmed with repeat A1c or another glucose test.",
  },
  "Estimated average glucose": {
    measures: "A calculated translation of A1c into the same mg/dL units used by glucose meters. It is not a separate blood measurement.",
    why: "It makes the A1c result easier to understand as an estimated daily average.",
    yours: "111 mg/dL is the calculated equivalent of the 5.5% A1c and is consistent with a non-diabetic A1c.",
    abnormal: "A high estimate follows a high A1c and may suggest prediabetes or diabetes. It may not match individual finger-stick readings because glucose varies throughout the day.",
    next: "Use the A1c and direct glucose measurements for clinical decisions. Improve glucose health through diet quality, activity, sleep, and weight management when needed.",
  },
  Glucose: {
    measures: "The concentration of glucose, the body's main circulating energy source, at the time of the blood draw.",
    why: "It screens for high or low blood sugar and helps assess diabetes and metabolic health.",
    yours: "92 mg/dL is within the printed range. If this was a fasting sample, it is also within the usual fasting range.",
    abnormal: "High glucose may reflect diabetes, stress, illness, medicines, or a nonfasting draw. Low glucose may occur with diabetes treatment, prolonged fasting, alcohol, hormone disorders, or serious illness.",
    next: "Interpret it according to fasting status and symptoms. Unexpected abnormalities are usually repeated or confirmed with A1c or an oral glucose-tolerance test before treatment.",
  },
  Creatinine: {
    measures: "A waste product from normal muscle metabolism that the kidneys filter from blood.",
    why: "It is used to estimate kidney filtration and is commonly included in metabolic panels and medication monitoring.",
    yours: "1.16 mg/dL is within the printed range.",
    abnormal: "High creatinine may reflect reduced kidney filtration, dehydration, urinary obstruction, muscle injury, supplements, or greater muscle mass. A low value can occur with low muscle mass or pregnancy.",
    next: "Interpret it with eGFR, hydration, medications, muscle mass, urine testing, and trends. Persistent abnormalities prompt kidney-focused evaluation.",
  },
  eGFR: {
    measures: "Estimated glomerular filtration rate, calculated from creatinine and demographic information to approximate kidney filtering capacity.",
    why: "It is a more useful kidney-function estimate than creatinine alone and helps stage chronic kidney disease when abnormalities persist.",
    yours: "86 mL/min is above 60. By itself, one value of 86 does not diagnose chronic kidney disease, especially with normal creatinine and no known urine marker of kidney damage.",
    abnormal: "A persistently low eGFR may reflect chronic kidney disease; an abrupt fall can indicate acute kidney injury. Hydration, medicines, illness, and muscle characteristics can affect the estimate.",
    next: "Trend the value. If concern exists, repeat it and check blood pressure and urine albumin-to-creatinine ratio. Protect kidney health by controlling blood pressure and diabetes and avoiding unnecessary kidney-toxic drugs.",
  },
  BUN: {
    measures: "Blood urea nitrogen, a waste product created when the body breaks down protein and removed mainly by the kidneys.",
    why: "It helps assess kidney function, hydration, and protein metabolism as part of a metabolic panel.",
    yours: "14 mg/dL is within the printed range.",
    abnormal: "High BUN may occur with dehydration, reduced kidney function, high protein breakdown or intake, gastrointestinal bleeding, or some medicines. Low BUN may occur with low protein intake, overhydration, pregnancy, or severe liver dysfunction.",
    next: "Interpret with creatinine, eGFR, hydration, diet, and symptoms. Correct the underlying cause rather than the BUN number itself.",
  },
  "BUN / creatinine ratio": {
    measures: "The relationship between BUN and creatinine, two waste markers influenced by kidneys and hydration.",
    why: "It can provide clues about dehydration, blood flow to the kidneys, protein breakdown, or other reasons BUN and creatinine differ.",
    yours: "12.1 is within the printed range.",
    abnormal: "A high ratio can occur with dehydration, gastrointestinal bleeding, or increased protein breakdown. A low ratio can occur with low protein intake, liver dysfunction, or disproportionate creatinine production. It is not diagnostic alone.",
    next: "Use the individual values and clinical context. Repeat or investigate only when the underlying markers or symptoms are concerning.",
  },
  Sodium: {
    measures: "The main electrolyte outside cells, important for fluid balance, nerves, muscles, and blood pressure.",
    why: "It is routinely checked to detect fluid or electrolyte disorders and monitor kidney, heart, hormone, and medication effects.",
    yours: "140 mEq/L is within the printed range.",
    abnormal: "Low or high sodium usually reflects an imbalance between body water and sodium rather than diet alone. Significant abnormalities can cause confusion, seizures, or other neurologic problems.",
    next: "Acute or marked abnormalities need prompt medical evaluation. Treatment depends on the cause and must be corrected at a controlled rate.",
  },
  Potassium: {
    measures: "An electrolyte essential for heart rhythm, nerve signaling, and muscle contraction.",
    why: "It is checked routinely and when monitoring kidney disease, heart conditions, or medicines that change potassium.",
    yours: "4.4 mEq/L is within the printed range.",
    abnormal: "Both high and low potassium can cause weakness and dangerous heart-rhythm changes. Causes include kidney problems, vomiting or diarrhea, hormone disorders, medicines, and sample-handling issues.",
    next: "Unexpected abnormalities are often repeated promptly and reviewed with medications, kidney function, and an ECG when clinically needed. Do not self-correct with potassium supplements.",
  },
  Chloride: {
    measures: "An electrolyte that works with sodium and bicarbonate to regulate fluid and acid-base balance.",
    why: "It is part of routine metabolic testing and helps evaluate hydration, kidney function, and acid-base disorders.",
    yours: "104 mEq/L is within the printed range.",
    abnormal: "High or low chloride can accompany dehydration, vomiting, diarrhea, kidney disease, or acid-base disturbances. It is interpreted with sodium and carbon dioxide.",
    next: "Address the underlying fluid, kidney, medication, or acid-base cause. Isolated mild changes often need confirmation rather than direct treatment.",
  },
  "Carbon dioxide": {
    measures: "Mostly bicarbonate in the blood, a major buffer that helps control acid-base balance.",
    why: "It helps assess metabolic acid-base status, breathing-related compensation, and kidney function.",
    yours: "31 mEq/L is at the upper limit of the printed range and is still in range.",
    abnormal: "Low values can occur with metabolic acidosis, diarrhea, or kidney problems. High values can occur with metabolic alkalosis, vomiting, diuretics, or compensation for chronic breathing problems.",
    next: "Interpret with chloride, anion gap, kidney function, breathing status, and medications. Persistent abnormalities may require blood-gas or cause-specific evaluation.",
  },
  "Anion gap": {
    measures: "A calculated difference between commonly measured positively and negatively charged electrolytes.",
    why: "It helps detect certain acid-base disorders, especially accumulation of unmeasured acids.",
    yours: "9.4 is within the printed range.",
    abnormal: "A high gap can occur with lactic acidosis, ketoacidosis, severe kidney dysfunction, or some toxins. A low gap is less common and may relate to low albumin, lab variation, or certain proteins or ions.",
    next: "No action is needed for an in-range result. An abnormal gap is interpreted urgently or routinely depending on symptoms and the rest of the metabolic panel.",
  },
  Calcium: {
    measures: "Total calcium in blood, including protein-bound and free calcium, which supports bones, nerves, muscles, and heart function.",
    why: "It screens for parathyroid, vitamin D, bone, kidney, and certain cancer-related disorders and is included in a CMP.",
    yours: "9.2 mg/dL is within the printed range.",
    abnormal: "High or low calcium can affect nerves and heart rhythm. Causes include parathyroid disease, vitamin D disorders, kidney disease, medicines, dehydration, and changes in albumin.",
    next: "Unexpected results are often repeated and interpreted with albumin or ionized calcium, parathyroid hormone, vitamin D, kidney function, and medications.",
  },
  AST: {
    measures: "An enzyme found in liver, muscle, heart, and other tissues that enters blood when cells are injured.",
    why: "It is used with ALT and other markers to look for liver or muscle injury and monitor medicines or disease.",
    yours: "24 U/L is within the printed range.",
    abnormal: "High AST can result from liver disease, alcohol-related injury, strenuous exercise, or muscle injury. It is not liver-specific.",
    next: "Interpret it with ALT, alkaline phosphatase, bilirubin, symptoms, alcohol, medicines, and exercise. Persistent elevation may require repeat testing or imaging.",
  },
  ALT: {
    measures: "An enzyme concentrated in liver cells that rises when those cells are injured.",
    why: "It is one of the main blood tests used to screen for and monitor liver injury.",
    yours: "40 U/L is within the printed range.",
    abnormal: "High ALT can occur with fatty liver disease, viral hepatitis, alcohol, medicines or supplements, and other liver injury. The degree of elevation does not always equal disease severity.",
    next: "Review trends and possible causes. Managing weight and metabolic health, limiting alcohol, and reviewing medicines may help when appropriate, but persistent elevation needs clinician evaluation.",
  },
  "Alkaline phosphatase": {
    measures: "An enzyme found mainly in bile ducts and bone, with smaller amounts in other tissues.",
    why: "It helps look for bile-flow problems or increased bone turnover as part of liver and metabolic testing.",
    yours: "82 U/L is within the printed range.",
    abnormal: "High values may come from bile-duct or liver disease, bone growth or disease, pregnancy, or healing fractures. Low values are less common and may involve nutrition, thyroid, or genetic factors.",
    next: "If abnormal, clinicians use bilirubin, GGT or enzyme fractionation, symptoms, and imaging to determine whether the source is liver or bone.",
  },
  "Total bilirubin": {
    measures: "A yellow waste product formed when old red blood cells are broken down and processed by the liver.",
    why: "It helps assess liver processing, bile flow, and increased red-cell breakdown.",
    yours: "0.67 mg/dL is within the printed range.",
    abnormal: "High bilirubin can cause jaundice and may result from liver disease, bile obstruction, hemolysis, or benign Gilbert syndrome. A low level is usually not concerning.",
    next: "If high, fractionated direct and indirect bilirubin plus liver tests, CBC, symptoms, and sometimes imaging help identify the cause.",
  },
  Protein: {
    measures: "The combined amount of albumin and globulin proteins in blood.",
    why: "It provides broad information about liver production, nutrition, immune proteins, kidney losses, and hydration.",
    yours: "7.1 g/dL is within the printed range.",
    abnormal: "Low total protein can occur with liver disease, kidney or intestinal protein loss, or malnutrition. High levels may reflect dehydration, chronic inflammation, infection, or abnormal immune proteins.",
    next: "Interpret with albumin, globulin, liver and kidney tests, hydration, and symptoms. Persistent unexplained abnormalities may require protein electrophoresis.",
  },
  Albumin: {
    measures: "The most abundant blood protein, made by the liver, which helps maintain fluid balance and transports many substances.",
    why: "It helps assess liver production, nutrition, inflammation, hydration, and protein loss through kidneys or intestines.",
    yours: "4.7 g/dL is within the printed range.",
    abnormal: "Low albumin may occur with inflammation, liver disease, kidney protein loss, malnutrition, or intestinal loss. High albumin usually reflects dehydration.",
    next: "Treat the underlying cause rather than taking protein solely to change the number. Urine protein, liver tests, nutrition, and inflammatory context may be checked when low.",
  },
  Globulin: {
    measures: "A calculated group of blood proteins that includes antibodies and transport proteins.",
    why: "It adds information about immune activity, liver function, nutrition, and protein disorders.",
    yours: "2.4 g/dL is within the printed range.",
    abnormal: "High globulin can occur with chronic inflammation, infection, liver disease, or abnormal antibody production. Low levels can occur with immune deficiency, liver disease, or protein loss.",
    next: "Persistent unexplained abnormalities may prompt immunoglobulin testing or serum protein electrophoresis, guided by symptoms and other results.",
  },
  "A/G ratio": {
    measures: "The ratio of albumin to globulin proteins in blood.",
    why: "It helps reveal whether an abnormal total protein pattern is driven more by albumin or globulins.",
    yours: "2.0 is within the printed range.",
    abnormal: "A low ratio can occur with low albumin or increased globulins from liver, kidney, inflammatory, or immune conditions. A high ratio can occur with low globulins or dehydration.",
    next: "Interpret the component values first. Evaluation targets the reason albumin or globulin is abnormal, not the ratio itself.",
  },
  TSH: {
    measures: "Thyroid-stimulating hormone from the pituitary gland, which signals the thyroid to make T4 and T3.",
    why: "It is usually the first-line screening test for an underactive or overactive thyroid.",
    yours: "2.520 uIU/mL is within the printed range and is consistent with normal pituitary-thyroid signaling.",
    abnormal: "High TSH often suggests an underactive thyroid, while low TSH may suggest an overactive thyroid, medication effect, or pituitary-related issue. Free hormone levels clarify the pattern.",
    next: "No correction is indicated from an in-range TSH alone. Abnormal results are usually repeated and interpreted with free T4, symptoms, medicines, pregnancy status, and antibodies.",
  },
  "Free T4": {
    measures: "The unbound portion of thyroxine, the main hormone produced by the thyroid and available to tissues.",
    why: "It is interpreted with TSH to identify and classify thyroid dysfunction.",
    yours: "0.97 ng/dL is within the printed range.",
    abnormal: "Low free T4 may occur with hypothyroidism or pituitary disease. High free T4 may occur with hyperthyroidism, excess thyroid medication, or assay interference.",
    next: "Interpret with TSH and symptoms. Repeat or specialist testing may be needed for a discordant pattern. High-dose biotin can interfere with some thyroid assays.",
  },
  "Free T3": {
    measures: "The unbound portion of triiodothyronine, the more active thyroid hormone.",
    why: "It can help evaluate suspected hyperthyroidism or clarify certain abnormal TSH and T4 patterns.",
    yours: "2.9 pg/mL is within the printed range.",
    abnormal: "High free T3 can occur in hyperthyroidism. Low values can occur during serious illness, calorie restriction, or hypothyroidism and are not usually used alone to diagnose an underactive thyroid.",
    next: "Use it with TSH, free T4, symptoms, and medication history. Treat the diagnosed thyroid condition rather than an isolated T3 result.",
  },
  "Anti-T peroxidase": {
    measures: "Antibodies directed against thyroid peroxidase, an enzyme needed to make thyroid hormones.",
    why: "It helps determine whether autoimmune thyroid disease, especially Hashimoto disease, is causing thyroid dysfunction.",
    yours: "9 IU/mL is below the printed cutoff, so this test does not show elevated TPO antibodies.",
    abnormal: "A positive result supports autoimmune thyroid disease but can occur in people with normal thyroid function. The antibody level itself does not measure disease severity.",
    next: "No treatment targets the antibody number. Monitor thyroid function when clinically appropriate and treat actual hormone dysfunction.",
  },
  "Anti-thyroglobulin": {
    measures: "Antibodies against thyroglobulin, a thyroid protein used to make hormones.",
    why: "It can support an autoimmune thyroid diagnosis and may affect interpretation of thyroglobulin monitoring in thyroid-cancer care.",
    yours: "Less than 1 IU/mL is below the printed cutoff and is reassuring.",
    abnormal: "Positive antibodies may occur with Hashimoto disease, Graves disease, or other autoimmune thyroid conditions, but they do not diagnose dysfunction by themselves.",
    next: "Use TSH and free thyroid hormones to guide care. There is no routine treatment to lower the antibody value itself.",
  },
  WBC: {
    measures: "The total number of white blood cells that participate in immune defense.",
    why: "It screens for infection, inflammation, bone-marrow disorders, immune conditions, and treatment effects.",
    yours: "7.7 K/uL is within the printed range.",
    abnormal: "A high WBC can occur with infection, inflammation, stress, smoking, steroids, or blood disorders. A low WBC can occur with viral illness, medicines, autoimmune disease, nutrient deficiency, or bone-marrow problems.",
    next: "Interpret with the differential, symptoms, medicines, and trends. Persistent or marked abnormalities may require repeat CBC, smear review, or hematology evaluation.",
  },
  RBC: {
    measures: "The number of red blood cells, which carry oxygen through hemoglobin.",
    why: "It helps evaluate anemia, excess red-cell production, dehydration, and bone-marrow or chronic disease.",
    yours: "5.15 M/uL is within the printed range.",
    abnormal: "Low RBC can indicate anemia from iron or vitamin deficiency, blood loss, kidney disease, inflammation, or marrow problems. High RBC may reflect dehydration, low oxygen, smoking, testosterone, or a marrow disorder.",
    next: "Interpret with hemoglobin, hematocrit, red-cell indices, symptoms, and trends. Treatment depends on the cause.",
  },
  Hemoglobin: {
    measures: "The iron-containing protein in red blood cells that carries oxygen.",
    why: "It is a primary measure used to detect anemia or an excessive red-cell concentration.",
    yours: "15.1 g/dL is within the printed range, so these results do not show anemia.",
    abnormal: "Low hemoglobin can cause fatigue or shortness of breath and may result from blood loss, iron or vitamin deficiency, kidney disease, inflammation, or marrow disorders. High values may reflect dehydration or chronic low oxygen.",
    next: "Investigate the cause using indices, iron and vitamin studies, kidney function, bleeding history, oxygen status, and trends before treating.",
  },
  Hematocrit: {
    measures: "The percentage of blood volume made up of red blood cells.",
    why: "It supports evaluation of anemia, dehydration, and excessive red-cell production.",
    yours: "46.2% is within the printed range.",
    abnormal: "Low hematocrit generally parallels anemia. High hematocrit can occur with dehydration, smoking, low-oxygen conditions, testosterone use, or a marrow disorder.",
    next: "Interpret with hemoglobin, RBC count, hydration, symptoms, and repeat trends. Address the underlying cause.",
  },
  MCV: {
    measures: "Mean corpuscular volume, the average size of red blood cells.",
    why: "It helps classify anemia as small-cell, normal-cell, or large-cell and narrows possible causes.",
    yours: "89.6 fL is within the printed range, indicating normally sized red blood cells.",
    abnormal: "Low MCV commonly occurs with iron deficiency or thalassemia. High MCV can occur with B12 or folate deficiency, alcohol, liver disease, thyroid disease, medicines, or marrow disorders.",
    next: "Use hemoglobin, RDW, iron studies, B12, folate, thyroid and liver tests, and history to identify the cause if abnormal.",
  },
  RDW: {
    measures: "Red-cell distribution width, which describes how much red blood-cell size varies.",
    why: "It helps distinguish types of anemia and can show a mixed or evolving red-cell problem.",
    yours: "13.8% is within the printed range, meaning red-cell sizes are relatively uniform.",
    abnormal: "A high RDW may occur with iron, B12, or folate deficiency, mixed deficiencies, recent blood loss, or recovery after treatment. A low RDW is usually not concerning.",
    next: "Interpret with MCV, hemoglobin, iron and vitamin studies. Treat the identified cause, not RDW itself.",
  },
  MCH: {
    measures: "Mean corpuscular hemoglobin, the average amount of hemoglobin in each red blood cell.",
    why: "It helps characterize anemia and usually changes along with red-cell size.",
    yours: "29 pg is within the printed range.",
    abnormal: "Low MCH often accompanies small red cells in iron deficiency or thalassemia. High MCH often accompanies large red cells and is interpreted with MCV.",
    next: "Use the complete CBC and iron or vitamin testing to find the cause. It is not treated as an isolated target.",
  },
  MCHC: {
    measures: "Mean corpuscular hemoglobin concentration, the average concentration of hemoglobin inside red blood cells.",
    why: "It helps classify anemia and assess how densely red cells are filled with hemoglobin.",
    yours: "33 g/dL is within the printed range.",
    abnormal: "Low MCHC can occur with iron deficiency and other hypochromic anemias. High MCHC is uncommon and may occur with spherocytosis, hemolysis, cold agglutinins, or sample issues.",
    next: "Interpret with the full CBC and sometimes a blood smear. Treat the underlying blood or nutrient disorder.",
  },
  Platelets: {
    measures: "The number of platelets, cell fragments that help form blood clots and stop bleeding.",
    why: "It screens for bleeding or clotting risk, bone-marrow problems, inflammation, and medication effects.",
    yours: "205 K/uL is within the printed range.",
    abnormal: "Very low platelets can increase bleeding risk. High platelets can be reactive to inflammation or iron deficiency or, less commonly, reflect a marrow disorder and may increase clotting risk.",
    next: "Unexpected results are often repeated and interpreted with symptoms, smear review, medicines, infection or inflammation, iron status, and trends.",
  },
  "Neutrophils (%)": {
    measures: "The percentage of white blood cells that are neutrophils, the rapid-response cells for many bacterial and fungal infections.",
    why: "It is part of the white-cell differential and shows the relative mix of immune-cell types.",
    yours: "47.5% is reported without a laboratory reference interval. The absolute neutrophil count is in range, which is the more clinically useful count.",
    abnormal: "A high percentage can occur with infection, inflammation, stress, or steroids. A low percentage may simply reflect more lymphocytes or may accompany low neutrophil production.",
    next: "Use the absolute neutrophil count, total WBC, symptoms, and trend rather than trying to change the percentage itself.",
  },
  "Bands (%)": {
    measures: "The percentage of white blood cells that are immature neutrophils, often called bands.",
    why: "It can show whether bone marrow is releasing young neutrophils during an acute immune response.",
    yours: "0.0% means no bands were reported and is consistent with the normal absolute band count.",
    abnormal: "An increased band percentage can occur with significant infection, inflammation, tissue injury, or marrow stimulation, but it is nonspecific.",
    next: "Interpret it with symptoms, total WBC, absolute neutrophils, and other clinical findings. The underlying illness is treated, not the band count.",
  },
  "Lymphocytes (%)": {
    measures: "The percentage of white blood cells that are lymphocytes, cells involved in antiviral defense, antibodies, and immune memory.",
    why: "It describes the relative white-cell mix and complements the absolute lymphocyte count.",
    yours: "44.9% is reported without a printed reference interval. Your absolute lymphocyte count is only minimally above its range.",
    abnormal: "A high percentage often accompanies viral illness or a lower neutrophil percentage. A low percentage may occur with acute stress, steroids, or immune suppression.",
    next: "Base follow-up on the absolute count, total WBC, symptoms, and persistence. Percentages can shift even when cell numbers are acceptable.",
  },
  "Monocytes (%)": {
    measures: "The percentage of white blood cells that are monocytes, cells that remove debris and participate in longer-term immune responses.",
    why: "It is part of the differential used to characterize infection, inflammation, and marrow patterns.",
    yours: "5.7% is reported without a printed percentage range, while the absolute monocyte count is in range.",
    abnormal: "Higher proportions can occur during recovery from infection, chronic inflammation, or some blood disorders. A low percentage alone is usually less informative.",
    next: "Use the absolute count, symptoms, and trend. Persistent marked abnormalities may prompt repeat CBC and smear review.",
  },
  "Eosinophils (%)": {
    measures: "The percentage of white blood cells that are eosinophils, cells involved in allergic responses and defense against certain parasites.",
    why: "It helps evaluate allergies, asthma, medicine reactions, parasitic infection, and certain inflammatory or blood disorders.",
    yours: "1.3% is reported without a printed percentage range, and the absolute eosinophil count is in range.",
    abnormal: "A high proportion can occur with allergies, asthma, eczema, drug reactions, parasites, and some immune or blood disorders.",
    next: "Interpret the absolute count with symptoms and exposures. Treatment targets the allergy, infection, medicine reaction, or other cause.",
  },
  "Basophils (%)": {
    measures: "The percentage of white blood cells that are basophils, rare cells involved in allergic and inflammatory signaling.",
    why: "It is routinely included in a white-cell differential and can add context to allergy, inflammation, or marrow disorders.",
    yours: "0.6% is reported without a printed percentage range, and the absolute basophil count is in range.",
    abnormal: "A high count may occur with allergies, chronic inflammation, low thyroid function, or rarely a marrow disorder. Percentage changes alone are often not significant.",
    next: "Use the absolute count and clinical context. Persistent absolute elevation may warrant repeat testing and further evaluation.",
  },
  "Other white cells (%)": {
    measures: "The percentage of white cells classified by the analyzer outside the routinely listed neutrophil, lymphocyte, monocyte, eosinophil, basophil, and band groups.",
    why: "It can flag an unusual cell population that may need manual review.",
    yours: "0.0% means no other white-cell population was reported.",
    abnormal: "A nonzero result can reflect analyzer classification, reactive cells, immature cells, or rarely abnormal blood cells and must be interpreted by the laboratory and clinician.",
    next: "No action is needed for zero. A flagged nonzero result may prompt a repeat CBC or manual peripheral-smear review.",
  },
  "Absolute neutrophils": {
    measures: "The number of neutrophils, white cells that provide rapid defense against many bacterial and fungal infections.",
    why: "It helps assess infection-fighting capacity and interpret changes in the total WBC count.",
    yours: "3.66 K/uL is within the printed range.",
    abnormal: "High counts can occur with infection, inflammation, stress, smoking, or steroids. Low counts can increase infection risk and may result from medicines, viral illness, autoimmune disease, nutrient deficiency, or marrow problems.",
    next: "Severity, symptoms, and trends matter. Fever with a severely low count requires urgent medical attention; milder abnormalities are usually repeated and evaluated for a cause.",
  },
  "Absolute bands": {
    measures: "The measured number of immature neutrophils in the blood.",
    why: "It helps assess whether marrow is releasing young infection-fighting cells during an acute response.",
    yours: "0.00 K/uL is within the printed range.",
    abnormal: "An elevated count may occur with acute infection, inflammation, major stress, or tissue injury. It does not identify the cause by itself.",
    next: "Interpret it with symptoms, cultures when appropriate, total WBC, and neutrophils. Treat the underlying condition.",
  },
  "Absolute lymphocytes": {
    measures: "The number of lymphocytes, white cells central to antiviral defense, antibodies, and immune memory.",
    why: "It helps interpret the white-cell differential and may identify immune responses or blood-cell disorders.",
    yours: "3.46 K/uL is only 0.06 above the printed upper limit, while the total WBC is normal. A small isolated elevation is often temporary.",
    abnormal: "High counts commonly occur after viral infections and less commonly with chronic infection or lymphoid blood disorders. Low counts can occur with acute illness, steroids, immune disorders, or some treatments.",
    next: "Trend it rather than trying to lower it. Repeat the CBC if clinically indicated, especially if it persists or is accompanied by swollen nodes, fever, night sweats, weight loss, or other abnormalities.",
  },
  "Absolute monocytes": {
    measures: "The number of monocytes, white cells that become macrophages and help clear debris and coordinate immune responses.",
    why: "It helps interpret the differential in infections, inflammation, recovery states, and some blood disorders.",
    yours: "0.44 K/uL is within the printed range.",
    abnormal: "High counts can occur with chronic infection, inflammation, recovery after acute infection, or some marrow disorders. Low counts may occur with marrow suppression or certain medicines.",
    next: "No action is needed for an in-range count. Persistent abnormalities are evaluated with symptoms, trends, medicines, and sometimes a smear.",
  },
  "Absolute eosinophils": {
    measures: "The number of eosinophils, white cells involved in allergy, asthma, medicine reactions, and parasite defense.",
    why: "It helps evaluate allergic, parasitic, inflammatory, and certain blood conditions.",
    yours: "0.10 K/uL is within the printed range.",
    abnormal: "High counts can occur with allergies, asthma, eczema, drug reactions, parasites, autoimmune disease, adrenal insufficiency, or some blood disorders.",
    next: "Evaluate exposures, medicines, travel, allergy symptoms, and persistence. Treat the identified cause rather than the cell count.",
  },
  "Absolute basophils": {
    measures: "The number of basophils, rare immune cells that release histamine and other inflammatory mediators.",
    why: "It is routinely included in the differential and may provide clues in allergy, inflammation, thyroid disease, or marrow disorders.",
    yours: "0.05 K/uL is within the printed range.",
    abnormal: "Persistent elevation can occur with allergic or inflammatory conditions and, rarely, myeloproliferative blood disorders. A low count is usually not concerning.",
    next: "No action is needed for this result. Persistent elevation is interpreted with the rest of the CBC, symptoms, thyroid testing, and sometimes a smear.",
  },
  "Absolute other white cells": {
    measures: "The measured number of white cells placed outside the standard differential categories by the analyzer.",
    why: "It can flag unexpected or immature cells that may require manual examination.",
    yours: "0.00 K/uL is exactly the printed reference value and means no other cell population was reported.",
    abnormal: "A nonzero or flagged value can represent reactive, immature, or abnormal cells, but analyzer classification is not a diagnosis.",
    next: "No action is needed for zero. A flagged value is usually reviewed with a repeat CBC and manual peripheral smear.",
  },
  "Total testosterone": {
    measures: "All testosterone in blood, including hormone bound to proteins and the smaller free portion.",
    why: "It may be checked for symptoms such as low libido, erectile problems, infertility, reduced muscle mass, delayed puberty, or suspected excess hormone.",
    yours: "424 ng/dL is within the printed range for this morning sample.",
    abnormal: "Low values in men can arise from testicular, pituitary, chronic-disease, obesity, sleep, medicine, or alcohol-related factors. High values may reflect supplements, steroids, or less commonly adrenal or testicular disease.",
    next: "Diagnose deficiency only when compatible symptoms and repeatedly low morning levels are present. Review sleep, weight, medicines, alcohol, and related pituitary hormones before considering treatment.",
  },
  "Free testosterone": {
    measures: "The small portion of testosterone not bound to proteins and more readily available to tissues.",
    why: "It can clarify testosterone status when total testosterone and symptoms do not match or SHBG is likely abnormal.",
    yours: "10.07 ng/dL is within the printed range.",
    abnormal: "Low or high free testosterone can reflect changes in total testosterone, SHBG, obesity, thyroid or liver disease, medicines, or hormone disorders.",
    next: "Interpret with morning total testosterone, SHBG, symptoms, and the assay method. Repeat confirmation and cause-focused evaluation come before hormone therapy.",
  },
  "% free testosterone": {
    measures: "The calculated percentage of total testosterone that is unbound rather than attached to proteins.",
    why: "It helps show how binding proteins affect the amount of biologically available hormone.",
    yours: "2.4% is within the printed range.",
    abnormal: "A low or high percentage often reflects an abnormal SHBG level rather than a change in testosterone production alone.",
    next: "Use total testosterone, free testosterone, SHBG, symptoms, and morning timing together. Do not treat the percentage in isolation.",
  },
  "Sex hormone binding globulin": {
    measures: "A liver-made protein that binds testosterone and other sex hormones and controls how much is free.",
    why: "It helps explain discordance between total testosterone, free testosterone, and symptoms.",
    yours: "22.5 nmol/L is within the printed range.",
    abnormal: "High SHBG can occur with aging, hyperthyroidism, liver disease, estrogen exposure, or low body weight. Low SHBG can occur with obesity, insulin resistance, hypothyroidism, androgen use, or some kidney conditions.",
    next: "Address the underlying thyroid, liver, metabolic, nutritional, or medication cause when present. Interpret hormone values together.",
  },
  "Morning cortisol": {
    measures: "Cortisol, an adrenal hormone involved in stress response, blood pressure, glucose regulation, and metabolism. It normally peaks in the morning.",
    why: "It may be checked when adrenal insufficiency or cortisol excess is suspected, or as part of a broader hormone evaluation.",
    yours: "10.10 ug/dL is within the laboratory's morning range for an 8:30 AM draw.",
    abnormal: "Low morning cortisol can raise concern for adrenal insufficiency, while high cortisol may reflect stress, illness, medication, or cortisol excess. A single value is not usually diagnostic.",
    next: "If symptoms create concern, clinicians use repeat timing and specialized tests such as ACTH stimulation, late-night salivary cortisol, or urine free cortisol. Do not try to alter cortisol with supplements based on one result.",
  },
  "Treponemal antibody total": {
    measures: "Antibodies that the immune system may make against Treponema pallidum, the bacterium that causes syphilis.",
    why: "It is used to screen for current or past syphilis infection, often as part of routine STI testing or testing after a possible exposure.",
    yours: "Non-reactive means no treponemal antibodies were detected in this sample. That is reassuring for the testing window represented.",
    abnormal: "A reactive result may represent current or previously treated syphilis and requires interpretation with a second test, history, symptoms, and prior treatment.",
    next: "No treatment is indicated from this non-reactive result. Retesting may be needed after a recent exposure because antibodies take time to become detectable. Confirmed infection is treated with clinician-prescribed antibiotics and partner follow-up.",
  },
  "Hepatitis B surface antigen": {
    measures: "A protein on the surface of hepatitis B virus that can be present during an active infection.",
    why: "It is used to look for current hepatitis B infection and is ideally interpreted with surface antibody and core antibody testing.",
    yours: "Negative means surface antigen was not detected, so this test does not show current hepatitis B infection.",
    abnormal: "A positive result can indicate acute or chronic hepatitis B, although recent vaccination can occasionally cause a temporary positive result.",
    next: "Your accompanying positive surface antibody pattern is consistent with immunity. A positive antigen would require a complete hepatitis B panel, liver evaluation, and specialist-guided monitoring or treatment.",
  },
  "Hepatitis B surface antibody": {
    measures: "Antibodies against the hepatitis B surface protein, which generally indicate immunity after vaccination or recovery from infection.",
    why: "It helps determine whether a person is immune to hepatitis B and is interpreted with surface antigen and, ideally, core antibody.",
    yours: "Positive surface antibody together with negative surface antigen is the pattern the report identifies as immunity to future hepatitis B infection.",
    abnormal: "A negative antibody can mean no immunity, waning detectable antibody, or an incomplete response. The complete three-test pattern is needed to distinguish vaccination, past infection, susceptibility, and active infection.",
    next: "No attempt to lower this antibody is needed. If immune status is uncertain or important for work or exposure risk, a clinician can review vaccination records and obtain the CDC-recommended triple panel.",
  },
  "Hepatitis C antibody": {
    measures: "Antibodies made after exposure to hepatitis C virus. It does not directly measure whether virus is currently present.",
    why: "It is the usual screening test for past or current hepatitis C exposure.",
    yours: "Negative means no hepatitis C antibodies were detected and there is no serologic evidence of current or past infection in this sample.",
    abnormal: "A positive antibody indicates prior exposure but cannot distinguish active infection from a cleared or successfully treated infection. An HCV RNA test determines whether infection is current.",
    next: "No action is usually needed unless exposure was recent or ongoing. A positive result is followed by HCV RNA testing; current infection can usually be cured with antiviral treatment.",
  },
  "HIV 1/2 antigen/antibody": {
    measures: "Both HIV-1 and HIV-2 antibodies and the HIV p24 antigen, which can appear earlier than antibodies.",
    why: "It is the standard laboratory screening approach for HIV and can detect infection earlier than an antibody-only test.",
    yours: "Non-reactive means no HIV antigen or antibodies were detected in this sample. It is reassuring for exposures outside the test's window period.",
    abnormal: "A reactive screening result does not establish the diagnosis by itself and is followed by confirmatory differentiation and sometimes nucleic-acid testing.",
    next: "No treatment is indicated from this result. Testing may need to be repeated after a recent exposure. Urgent post-exposure prophylaxis should be discussed immediately when a significant exposure occurred within 72 hours.",
  },
  "Gonorrhea RNA": {
    measures: "Genetic material from Neisseria gonorrhoeae using a nucleic-acid amplification test on the submitted urine sample.",
    why: "It screens for or helps diagnose gonorrhea, which often causes no symptoms and can be transmitted to partners.",
    yours: "Negative means gonorrhea genetic material was not detected in the urine sample.",
    abnormal: "A positive result indicates infection at the sampled site. Untreated infection can cause pelvic inflammatory disease, infertility, testicular complications, disseminated infection, and ongoing transmission.",
    next: "A positive result requires guideline-directed antibiotics, partner notification and treatment, temporary sexual abstinence as advised, and recommended retesting. A urine test does not rule out infection at an untested throat or rectal site.",
  },
  "Chlamydia RNA": {
    measures: "Genetic material from Chlamydia trachomatis using a nucleic-acid amplification test on the submitted urine sample.",
    why: "It screens for or helps diagnose chlamydia, a common STI that frequently has no symptoms.",
    yours: "Negative means chlamydia genetic material was not detected in the urine sample.",
    abnormal: "A positive result indicates infection at the sampled site. Untreated infection can cause pelvic inflammatory disease, infertility, or inflammation near the testicle and can be passed to partners.",
    next: "A positive result is treated with clinician-prescribed antibiotics, partner management, and recommended retesting. A urine result does not exclude an infection at an untested throat or rectal site.",
  },
  "Trichomonas RNA": {
    measures: "Genetic material from Trichomonas vaginalis using a nucleic-acid amplification test on the submitted urine sample.",
    why: "It is used to diagnose or screen for trichomoniasis, which may cause genital or urinary symptoms but is often silent.",
    yours: "Negative means trichomonas genetic material was not detected in the urine sample.",
    abnormal: "A positive result indicates infection. Untreated infection can cause persistent genital inflammation, facilitate transmission, and increase susceptibility to other STIs.",
    next: "A positive result is treated with a clinician-prescribed antimicrobial, with partner treatment and temporary abstinence as advised to prevent reinfection. Retesting decisions depend on sex and risk.",
  },
};
